// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Infrastructure.EFCore;

#nullable disable

namespace MoneyMangement.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(MoneyContext))]
    [Migration("20221024114051_addmoney")]
    partial class addmoney
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MoneyManagement.Domain.MoneyDomin.Money", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISO_Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SaveDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Moneys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Country = "افغانستان",
                            ISO_Code = "AFN",
                            Name = "افغانی",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "افغانی",
                            Status = true,
                            Symbol = "؋",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Country = "ایران",
                            ISO_Code = "IRR",
                            Name = "ریال",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "ریال",
                            Status = true,
                            Symbol = "ریال",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Country = "چین",
                            ISO_Code = "CNY",
                            Name = "یوآن",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "یوآن",
                            Status = true,
                            Symbol = "¥",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Country = "هندوستان",
                            ISO_Code = "INR",
                            Name = "روپیه",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "روپیه",
                            Status = true,
                            Symbol = "₹",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Country = "پاکستان",
                            ISO_Code = "PKR",
                            Name = "روپیه",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "روپیه",
                            Status = true,
                            Symbol = "₨",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Country = "اروپا",
                            ISO_Code = "EUR",
                            Name = "یورو",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "یورو",
                            Status = true,
                            Symbol = "€",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Country = "بریتانیا",
                            ISO_Code = "GBP",
                            Name = "پوند",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "پوند",
                            Status = true,
                            Symbol = "£",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Country = "ایالات متحده امریکا",
                            ISO_Code = "USD",
                            Name = "دلار",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "دلار",
                            Status = true,
                            Symbol = "$",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Country = "ترکیه",
                            ISO_Code = "TRY",
                            Name = "لیره",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "لیره",
                            Status = true,
                            Symbol = "₺",
                            User_Id = 1
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Country = "روسیه",
                            ISO_Code = "RUB",
                            Name = "روبل",
                            SaveDate = "1401/08/02 16:10:51",
                            Slug = "روبل",
                            Status = true,
                            Symbol = "₽",
                            User_Id = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
